version: '3.8'
services:
  elastic:
    image: elasticsearch:8.15.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"